### ISSUE TITLE
Link to repo is missing in pub.dev

### ISSUE THREAD

**Issue by guyluz11** [OpenIoTHub/matter#1]
Link to this repository is missing in [pub.dev](https://pub.dev/packages/matter) 

This package 
![Screenshot_20230912_214053_Firefox](https://github.com/OpenIoTHub/matter_dart/assets/9304740/9e8efca3-8463-4887-b003-0de2f0ba7aff)

How it's supposed to look like
![Screenshot_20230912_214232_Firefox](https://github.com/OpenIoTHub/matter_dart/assets/9304740/bebe4500-ac7a-4deb-80ac-45f9368ebf36)

**Comment by IoTServ** [comment]
Thank you for your reminder. It has just been resolved👏
