### ISSUE TITLE
Documentation needed for plugin implementation

### ISSUE THREAD

**Issue by void-henil** [OpenIoTHub/matter#2]
Hi there,

First, thank you for creating this valuable plugin that supports Matter across all platforms (Android, iOS, desktop, and web). 

I'm trying to implement the plugin in my project but having difficulty getting started since there's currently no documentation available on pub.dev. Would it be possible to add basic documentation covering:

1. Basic usage examples and common use cases
2. Required configurations/permissions for different platforms
3. Any platform-specific considerations or limitations

I believe having documentation would help many developers like me who want to integrate Matter support in their cross-platform applications.

Thanks for your time!

**Comment by guyluz11** [comment]
I think this package is a placeholder as I see no code in the lib folder.

Let me know if you find any other way to control Matter devices using flutter or even better Dart native.
